os: linux
arch:
  - arm64
language: node_js
node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

deploy:
  - provider: pages
    target_branch: master
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: build/
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|webpack.*)$
  - provider: pages
    target_branch: gh-pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: build/
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|webpack.*)$
