name: CI
on:
  push:
    branches:
      - develop
      - 'webpack.*'
    paths-ignore:
      - 'README.md'
env:
  CI: true
jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Build
        run: yarn && yarn build
      - name: Release
        uses: actions/upload-artifact@master
        with:
          name: trackmasters
          path: build
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download
        uses: actions/download-artifact@master
        with:
          name: trackmasters
          path: build
      - name: GitHub Pages Status Check
        uses: crazy-max/ghaction-github-status@v2
        with:
          pages_threshold: major_outage
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: master
          cname: trackmasters.cz
          full_commit_message: ${{ github.event.head_commit.message }}